image: python:3

before_script:
  - apt-get update -qy
  - apt-get install -y python-dev python-pip
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - python product_microservice/manage.py makemigrations
  - python product_microservice/manage.py migrate

tests:
  script:
    - python product_microservice/manage.py test

integration-dev:
  services:
  - integravendas/login-microservice
  - integravendas/order-microservice
  - integravendas/product-microservice
  - integravendas/api-gateway

  script:
    - curl -I http://localhost:8000

# runserver:
#   script:
#     - python product_microservice/manage.py runserver 0.0.0.0:8000
