image: python:3

before_script:
  - pip install -r product_microservice/requirements/dev.txt
  - python product_microservice/manage.py makemigrations
  - python product_microservice/manage.py migrate

tests:
  script:
    - cd product_microservice && python manage.py test
