image: docker:stable

stages:
  - test
  - publish
  - deploy

services:
  - docker:dind
  - docker:python:3

before_script:
  - docker info

unit test:
  stage: test
  script:
    - echo HELLO TESTS

deploy staging:
  stage: deploy
  only:
    - dev
    - tags
  except:
    - master
  script:
    - echo Hello deploy stag

deploy production:
  stage: deploy
  only:
    refs:
      - master
      - tags
    variables:
      - $CI_COMMIT_TAG =~ /^*/
  except:
    - dev
  script:
    - echo Hello deploy PRODUCTION

publish:
  only:
    - master
    - merge-requests
  stage: publish
  script:
    - echo Hello PUBLISH
    # - sh run-publish-docker.sh