image: python:3

stages:
  - test
  - deploy

unit test:
  stage: test
  script:
    - echo HELLO TESTS

deploy staging:
  stage: deploy
  only:
    - dev
  script:
    - echo Hello deploy stag

deploy production:
  stage: deploy
  only:
    - $CI_COMMIT_TAG =~ /*.*.*/
  script:
    - echo Hello deploy PRODUCTION
    - echo $CI_COMMIT_TAG

deploy production2:
  stage: deploy
  only:
    - tags
  script:
    - echo Hello deploy PRODUCTION
    - echo $CI_COMMIT_TAG
