image: docker:stable

services:
  - docker:dind
  - docker:ubuntu

before_script:
  - docker info

publish:
  only:
    - master
    - merge-requests
  stage: build
  script:
    - sh run-publish-docker.sh