image: docker:stable

services:
  - docker:dind

before_script:
  - docker info
  - apt-get -y update && apt-get -y install git

publish:
  only:
    - master
    - merge-requests
  stage: build
  script:
    - sh run-publish-docker.sh