
language: python
python:
  - "3.4"

install: 
  - pip install -r requirements.txt

virtualenv:
  system_site_packages: true

jobs:
  include:
    - stage: "Tests"                # naming the Tests stage
      name: "Unit Tests"            # names the first Tests stage job
      script: sh run-tests.sh
    - stage: deploy
      name: "Deploy to GCP"
      script: echo Hello-From-Mars