
language: python
python:
  - "3.4"

cache: pip

install: 
  - pip install -r product_microservice/requirements/dev.txt

virtualenv:
  system_site_packages: true

stages:
  - test
  - name: publish-docs
    if: branch = master
  - name: test-coverage
    if: branch = master
  - name: docker-image-update
    if: branch = master


jobs:
  include:
    - stage: "Tests"
      name: "Unit Tests"
      script: sh run-tests.sh
      
    - stage: publish-docs
      script:
        - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then sh run-publish-pages.sh; fi'
    
    - stage: test-coverage
      name: "Updating test coverage"
      script:
        - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then sh run-tests.sh; fi'
        - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then cd product_microservice && codecov -t ${CODECOV_TOKEN}; fi'