
language: python
python:
  - "3.6"

cache: pip

install: 
  - pip install -r requirements.txt

virtualenv:
  system_site_packages: true

stages:
  - test
  - name: publish-docs
    if: branch = master

jobs:
  include:
    - stage: "Tests"
      name: "Unit Tests"
      install:
        - pip install --upgrade pip
        - pip install -r requirements.txt
        - pip install tox
      env:
        - TOXENV=django20
        - TOXENV=coverage
      script: cd product_microservice && tox
      
    - stage: publish-docs
      script: 
        - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then sh run-publish-pages.sh; fi'