jobs:
  include:
    - stage: "Tests"                # naming the Tests stage
      name: "Unit Tests"            # names the first Tests stage job
      script: python product_microservice/manage.py test
    - stage: deploy
      name: "Deploy to GCP"
      script: echo Hello-From-Mars